name: pokemon-randomizer

type: nodejs:18

disk: 512

hooks:
    build: |
        mkdir -p OnlineUniversalPokemonRandomizerPlatform
        cp randomizer.jar OnlineUniversalPokemonRandomizerPlatform/
        cp randomizer.jar.js OnlineUniversalPokemonRandomizerPlatform/
        # Make sure settings directory is also copied if it exists
        if [ -d "settings" ]; then
            cp -r settings OnlineUniversalPokemonRandomizerPlatform/
        fi

web:
    locations:
        "/":
            root: ""
            index:
                - index.html
            expires: 1h
            scripts: false
            allow: true
            passthru: false
            headers:
                # Enable cross-origin requests
                Access-Control-Allow-Origin: "*"
                Access-Control-Allow-Methods: "GET, POST, OPTIONS"
                # Add storage permission policy
                Permissions-Policy: "interest-cohort=(), accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
