name: pokemon-randomizer

type: nodejs:18

disk: 512

web:
    locations:
        "/":
            root: ""
            index:
                - index.html
            expires: 1h
            scripts: false
            allow: true
            passthru: false
            headers:
                # Removed security headers that were causing iframe issues
                Access-Control-Allow-Origin: "*"
                Access-Control-Allow-Methods: "GET, POST, OPTIONS"
