name: pokemon-randomizer

type: python:3.9

disk: 512

dependencies:
    python3:
        flask: "*"

hooks:
    build: |
        # Create a minimal Flask server
        cat > server.py << 'EOL'
        from flask import Flask, send_from_directory

        app = Flask(__name__)

        # Add security headers
        @app.after_request
        def add_security_headers(response):
            response.headers['Cross-Origin-Opener-Policy'] = 'same-origin'
            response.headers['Cross-Origin-Embedder-Policy'] = 'require-corp'
            return response

        # Serve static files
        @app.route('/<path:path>')
        def serve_file(path):
            return send_from_directory('.', path)

        # Serve index.html
        @app.route('/')
        def serve_index():
            return send_from_directory('.', 'index.html')

        if __name__ == '__main__':
            app.run(host='0.0.0.0', port=8888)
        EOL

web:
    upstream:
        socket_family: tcp
        protocol: http
    commands:
        start: python server.py
    locations:
        "/":
            passthru: true
            scripts: false
            allow: true
