name: pokemon-randomizer

type: python:3.9

disk: 512

web:
    locations:
        "/":
            root: ""
            index:
                - index.html
            expires: 1h
            scripts: false
            allow: true
